### ISSUE TITLE
Unable to Access the wannier-berri.org web site.

### ISSUE THREAD

**Issue by churlhilyi** [wannier-berri/wannier-berri-org#14]
Hello.

I'm currently experiencing issues with accessing the wannier-berri.org website. The site isn't loading, and a message on the screen stating, "Be back soon! This website is under maintenance. Check back tomorrow!" I've checked my internet connection and tried accessing the site from multiple devices, but I keep getting the same message.

Could you please look into this issue and provide any potential solutions or updates regarding this problem?

**Comment by elchatz** [comment]
You can always download the offline version from this repository.

**Comment by churlhilyi** [comment]
Okay. I will use the offline version.
Thanks a lot.  @elchatz

**Comment by stepan-tsirkin** [comment]
Just in case you have issues compiling the html, there is a compiled zip here : 
https://github.com/wannier-berri/wannier-berri-org/blob/offline/WBorg.zip
